### ISSUE TITLE
Unable to fetch metrics, SSL errors despite setting environment variable to disable it

### ISSUE THREAD

**Issue by Isolyth** [esanchezm/prometheus-qbittorrent-exporter#63]
Here is the docker compose file I'm using
```
qbittorrent-exporter:
    image: esanchezm/prometheus-qbittorrent-exporter
    environment:
      - VERIFY_WEBUI_CERTIFICATE=False
      - QBITTORRENT_HOST=192.168.10.3
      - QBITTORRENT_PORT=8088
      - QBITTORRENT_USER=admin
      - QBITTORRENT_PASSWORD=password
    ports:
      - 8000:8000
```
However, when I run my stack, I get endless repeats of 
`{"asctime": "2024-10-10 23:31:52", "levelname": "WARNING", "message": "Retrying (Retry(total=0, connect=1, read=1, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /api/v2/sync/maindata", "taskName": null}`
and 
`{"asctime": "2024-10-10 23:31:38", "levelname": "ERROR", "message": "Couldn't fetch torrents: Failed to connect to qBittorrent. This is likely due to using an untrusted certificate (likely self-signed) for HTTPS qBittorrent WebUI. To suppress this error (and skip certificate verification consequently exposing the HTTPS connection to man-in-the-middle attacks), set VERIFY_WEBUI_CERTIFICATE=False when instantiating Client or set environment variable QBITTORRENTAPI_DO_NOT_VERIFY_WEBUI_CERTIFICATE to a non-null value. SSL Error: SSLError(MaxRetryError(\"HTTPSConnectionPool(host='192.168.10.3', port=8088): Max retries exceeded with url: /api/v2/torrents/info (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))\"))", "taskName": null}`
