### ISSUE TITLE
Failed to connect to qBittorrent

### ISSUE THREAD

**Issue by TegridyTate** [esanchezm/prometheus-qbittorrent-exporter#75]
I've been trying to setup this image in my existing docker-compose:
```
    qbittorrent:
      image: linuxserver/qbittorrent
      container_name: qbittorrent
      environment:
        - PUID=1000
        - PGID=1000
        - WEBUI_PORT=8080
        - TZ=Europe/Amsterdam
      volumes:
        - ./qbittorrent/config:/config
        - /mnt/merged_plex/qbittorrent:/downloads
      # ports:
      #   - 8080:8080
      #   - 6881:6881
      # networks:
      #   - bridge
      network_mode: "service:wireguard-pia"
      restart: unless-stopped

    qbittorrent-exporter:
      image: ghcr.io/esanchezm/prometheus-qbittorrent-exporter:latest
      container_name: qbittorrent-exporter
      environment:
        - PUID=1000
        - PGID=1000
        - EXPORTER_LOG_LEVEL=DEBUG
        - QBITTORRENT_PORT=8080
        - QBITTORRENT_HOST=${LOCAL_IP}
        - QBITTORRENT_PASS=${QBITTORRENT_PASSWORD}
        - QBITTORRENT_USER=${QBITTORRENT_USERNAME}
      volumes:
        - ./qbittorrent-exporter:/config
      ports:
        - 8000:8000
      networks:
        - bridge
      restart: unless-stopped
```

The ports and network bridge are commented out because I recently added PIA VPN to my setup and route qbittorrent traffic through the VPN, but this isn't the culprit. I double checked by reverting it back to not using my VPN, but it results in the same error. Also, I set it up such that services on my network can still access anything using the VPN using the same local ip and port.

When I try to use this qbittorrent exporter, the logs show lots of failed attempts to authenticate/connect to qBittorrent:
```
...
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Detecting scheme for URL...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Starting new HTTP connection (1): 192.168.178.14:8080", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "http://192.168.178.14:8080 \"HEAD / HTTP/11\" 200 0", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Using HTTP scheme", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Base URL: http://192.168.178.14:8080/", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Starting new HTTP connection (1): 192.168.178.14:8080", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "http://192.168.178.14:8080 \"POST /api/v2/auth/login HTTP/11\" 403 78", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Login may have expired...attempting new login", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Re-initializing context...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Parsed user URL: ParseResult(scheme='http', netloc='192.168.178.14:8080', path='', params='', query='', fragment='')", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Detecting scheme for URL...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Starting new HTTP connection (1): 192.168.178.14:8080", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "http://192.168.178.14:8080 \"HEAD / HTTP/11\" 200 0", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Using HTTP scheme", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Base URL: http://192.168.178.14:8080/", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Starting new HTTP connection (1): 192.168.178.14:8080", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "http://192.168.178.14:8080 \"POST /api/v2/auth/login HTTP/11\" 403 78", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Login may have expired...attempting new login", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Re-initializing context...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Parsed user URL: ParseResult(scheme='http', netloc='192.168.178.14:8080', path='', params='', query='', fragment='')", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Detecting scheme for URL...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Starting new HTTP connection (1): 192.168.178.14:8080", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "http://192.168.178.14:8080 \"HEAD / HTTP/11\" 200 0", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Using HTTP scheme", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Base URL: http://192.168.178.14:8080/", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Starting new HTTP connection (1): 192.168.178.14:8080", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "http://192.168.178.14:8080 \"POST /api/v2/auth/login HTTP/11\" 403 78", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Login may have expired...attempting new login", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Re-initializing context...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Parsed user URL: ParseResult(scheme='http', netloc='192.168.178.14:8080', path='', params='', query='', fragment='')", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Detecting scheme for URL...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Starting new HTTP connection (1): 192.168.178.14:8080", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Retry attempt 1", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Re-initializing context...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Parsed user URL: ParseResult(scheme='http', netloc='192.168.178.14:8080', path='', params='', query='', fragment='')", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Detecting scheme for URL...", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Starting new HTTP connection (1): 192.168.178.14:8080", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "DEBUG", "message": "Failed to connect to qBittorrent. Unknown Error: RecursionError('maximum recursion depth exceeded')", "taskName": null}
{"asctime": "2025-01-01 23:16:37", "levelname": "ERROR", "message": "Couldn't fetch torrents: Failed to connect to qBittorrent. Unknown Error: RecursionError('maximum recursion depth exceeded')", "taskName": null}
```

I've gone into the docker container to check if I could ping my qbittorrent service at `192.168.178.14:8080` and that works fine.

I can also make a curl request like so `curl -d "username=${QBITTORRENT_USER}&password=${QBITTORRENT_PASS}" http://${QBITTORRENT_HOST}:${QBITTORRENT_PORT}/api/v2/app/version` confirming that the environment variables are being passed correctly to the container and that they are set correctly.

Does anyone know how I could fix this?
