### ISSUE TITLE
Trouble Getting Started

### ISSUE THREAD

**Issue by Brancliff** [esanchezm/prometheus-qbittorrent-exporter#81]
Hey! Cool project here. There's another one that does a similar thing but it seems to have been abandoned (and I couldn't set that up either lol) I'm not sure what's the problem in my setup, but I've come with logs, so hopefully someone who's well-versed in this stuff will be able to help me out

- I've got a computer and a NAS
- The NAS runs docker, grafana, and [arch-qbittorrentvpn](https://github.com/binhex/arch-qbittorrentvpn)
- When on my LAN, I access qbittorrent from my NAS' static IP, over HTTP through the web browser, at http://192.168.10.20:5000
- There aren't many settings to configure so there's not much that can go wrong but somehow I've still messed it up :/

Here's the docker-compose:
```
services:  
  prometheus:
    image: docker.io/prom/prometheus:v3.1.0
    user: 1000:1000
    container_name: grafana-prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - /path/to/Grafana/Prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - /path/to/Grafana/Prometheus/Data:/prometheus
    restart: no
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: grafana-node-exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
  prometheus-qbittorrent-exporter:
    image: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
    container_name: grafana-prometheus-qbittorrent
#    network_mode: host
    environment:
    - EXPORTER_LOG_LEVEL=DEBUG
    - QBITTORRENT_PORT=5010
    - QBITTORRENT_HOST=192.168.10.20
    - QBITTORRENT_USER=xxxxxxx
    - QBITTORRENT_PASS=xxxxxxx
    - QBITTORRENT_SSL=False
    ports:
    - 7001:8000
    volumes:
      - /path/to/Grafana/Prometheus:/config
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
```

On another stack:
```
  arch-qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn:4.6.5-1-07
    container_name: qbittorrentvpn
    volumes:
      - /path/to/Downloads:/downloads
    ports:
      - 5000:5000
```

The promethus.yaml:
```
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['myapi:6003']
    metrics_path: '/tam-metrics'
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']
  - job_name: "qbittorrent_exporter"
    static_configs:
        - targets: ['arch-qbittorrentvpn:5000']
```

And the logs from the container:
```
Exporter is starting up | asctime=2025-02-04 11:40:49 levelname=INFO taskName=null
Parsed user URL: ParseResult(scheme='http', netloc='192.168.10.20:5000', path='', params='', query='', fragment='') | asctime=2025-02-04 11:40:49 levelname=DEBUG taskName=null
Detecting scheme for URL... | asctime=2025-02-04 11:40:49 levelname=DEBUG taskName=null
Starting new HTTP connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:40:49 levelname=DEBUG taskName=null
Incremented Retry for (url='/'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:41:05 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c40116a0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': / | asctime=2025-02-04 11:41:05 levelname=WARNING taskName=null
Starting new HTTP connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:41:05 levelname=DEBUG taskName=null
Failed connection attempt with HTTP | asctime=2025-02-04 11:41:20 levelname=DEBUG taskName=null
Starting new HTTPS connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:41:20 levelname=DEBUG taskName=null
Incremented Retry for (url='/'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:41:35 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc6c4011d30>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': / | asctime=2025-02-04 11:41:35 levelname=WARNING taskName=null
Starting new HTTPS connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:41:35 levelname=DEBUG taskName=null
Failed connection attempt with HTTPS | asctime=2025-02-04 11:41:50 levelname=DEBUG taskName=null
Using HTTP scheme | asctime=2025-02-04 11:41:50 levelname=DEBUG taskName=null
Base URL: http://192.168.10.20:5000/ | asctime=2025-02-04 11:41:50 levelname=DEBUG taskName=null
Starting new HTTP connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:41:50 levelname=DEBUG taskName=null
Incremented Retry for (url='/api/v2/sync/maindata'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:42:05 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3cac2d0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': /api/v2/sync/maindata | asctime=2025-02-04 11:42:05 levelname=WARNING taskName=null
Starting new HTTP connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:42:05 levelname=DEBUG taskName=null
Retry attempt 1 | asctime=2025-02-04 11:42:20 levelname=DEBUG taskName=null
Re-initializing context... | asctime=2025-02-04 11:42:20 levelname=DEBUG taskName=null
Parsed user URL: ParseResult(scheme='http', netloc='192.168.10.20:5000', path='', params='', query='', fragment='') | asctime=2025-02-04 11:42:20 levelname=DEBUG taskName=null
Detecting scheme for URL... | asctime=2025-02-04 11:42:20 levelname=DEBUG taskName=null
Starting new HTTP connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:42:20 levelname=DEBUG taskName=null
Incremented Retry for (url='/'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:42:35 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ffe9e0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': / | asctime=2025-02-04 11:42:35 levelname=WARNING taskName=null
Starting new HTTP connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:42:35 levelname=DEBUG taskName=null
Failed connection attempt with HTTP | asctime=2025-02-04 11:42:50 levelname=DEBUG taskName=null
Starting new HTTPS connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:42:51 levelname=DEBUG taskName=null
Incremented Retry for (url='/'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:43:06 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc6c40079d0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': / | asctime=2025-02-04 11:43:06 levelname=WARNING taskName=null
Starting new HTTPS connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:43:06 levelname=DEBUG taskName=null
Failed connection attempt with HTTPS | asctime=2025-02-04 11:43:21 levelname=DEBUG taskName=null
Using HTTP scheme | asctime=2025-02-04 11:43:21 levelname=DEBUG taskName=null
Base URL: http://192.168.10.20:5000/ | asctime=2025-02-04 11:43:21 levelname=DEBUG taskName=null
Starting new HTTP connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:43:21 levelname=DEBUG taskName=null
Incremented Retry for (url='/api/v2/sync/maindata'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:43:36 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c400b680>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': /api/v2/sync/maindata | asctime=2025-02-04 11:43:36 levelname=WARNING taskName=null
Starting new HTTP connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:43:36 levelname=DEBUG taskName=null
Failed to connect to qBittorrent. Unknown Error: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.10.20', port=5014): Max retries exceeded with url: /api/v2/sync/maindata (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c400b130>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)'))")) | asctime=2025-02-04 11:43:51 levelname=DEBUG taskName=null
Couldn't get server info: Failed to connect to qBittorrent. Unknown Error: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.10.20', port=5014): Max retries exceeded with url: /api/v2/sync/maindata (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c400b130>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)'))")) | asctime=2025-02-04 11:43:51 levelname=ERROR taskName=null
Starting new HTTP connection (3): 192.168.10.20:5000 | asctime=2025-02-04 11:43:51 levelname=DEBUG taskName=null
Incremented Retry for (url='/api/v2/app/webapiVersion'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:44:06 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c400acf0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': /api/v2/app/webapiVersion | asctime=2025-02-04 11:44:06 levelname=WARNING taskName=null
Starting new HTTP connection (4): 192.168.10.20:5000 | asctime=2025-02-04 11:44:06 levelname=DEBUG taskName=null
Retry attempt 1 | asctime=2025-02-04 11:44:21 levelname=DEBUG taskName=null
Re-initializing context... | asctime=2025-02-04 11:44:21 levelname=DEBUG taskName=null
Parsed user URL: ParseResult(scheme='http', netloc='192.168.10.20:5000', path='', params='', query='', fragment='') | asctime=2025-02-04 11:44:21 levelname=DEBUG taskName=null
Detecting scheme for URL... | asctime=2025-02-04 11:44:21 levelname=DEBUG taskName=null
Starting new HTTP connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:44:21 levelname=DEBUG taskName=null
Incremented Retry for (url='/'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:44:36 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c400bac0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': / | asctime=2025-02-04 11:44:36 levelname=WARNING taskName=null
Starting new HTTP connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:44:36 levelname=DEBUG taskName=null
Failed connection attempt with HTTP | asctime=2025-02-04 11:44:52 levelname=DEBUG taskName=null
Starting new HTTPS connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:44:52 levelname=DEBUG taskName=null
Incremented Retry for (url='/'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:45:07 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc6c4006710>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': / | asctime=2025-02-04 11:45:07 levelname=WARNING taskName=null
Starting new HTTPS connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:45:07 levelname=DEBUG taskName=null
Failed connection attempt with HTTPS | asctime=2025-02-04 11:45:22 levelname=DEBUG taskName=null
Using HTTP scheme | asctime=2025-02-04 11:45:22 levelname=DEBUG taskName=null
Base URL: http://192.168.10.20:5000/ | asctime=2025-02-04 11:45:22 levelname=DEBUG taskName=null
Starting new HTTP connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:45:22 levelname=DEBUG taskName=null
Incremented Retry for (url='/api/v2/app/webapiVersion'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:45:37 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ccc160>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': /api/v2/app/webapiVersion | asctime=2025-02-04 11:45:37 levelname=WARNING taskName=null
Starting new HTTP connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:45:37 levelname=DEBUG taskName=null
Failed to connect to qBittorrent. Unknown Error: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.10.20', port=5014): Max retries exceeded with url: /api/v2/app/webapiVersion (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ccc380>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)'))")) | asctime=2025-02-04 11:45:52 levelname=DEBUG taskName=null
Couldn't fetch categories: Failed to connect to qBittorrent. Unknown Error: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.10.20', port=5014): Max retries exceeded with url: /api/v2/app/webapiVersion (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ccc380>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)'))")) | asctime=2025-02-04 11:45:52 levelname=ERROR taskName=null
Starting new HTTP connection (3): 192.168.10.20:5000 | asctime=2025-02-04 11:45:52 levelname=DEBUG taskName=null
Incremented Retry for (url='/api/v2/torrents/info'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:46:07 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ccc7c0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': /api/v2/torrents/info | asctime=2025-02-04 11:46:07 levelname=WARNING taskName=null
Starting new HTTP connection (4): 192.168.10.20:5000 | asctime=2025-02-04 11:46:07 levelname=DEBUG taskName=null
Retry attempt 1 | asctime=2025-02-04 11:46:22 levelname=DEBUG taskName=null
Re-initializing context... | asctime=2025-02-04 11:46:22 levelname=DEBUG taskName=null
Parsed user URL: ParseResult(scheme='http', netloc='192.168.10.20:5000', path='', params='', query='', fragment='') | asctime=2025-02-04 11:46:22 levelname=DEBUG taskName=null
Detecting scheme for URL... | asctime=2025-02-04 11:46:22 levelname=DEBUG taskName=null
Starting new HTTP connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:46:22 levelname=DEBUG taskName=null
Incremented Retry for (url='/'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:46:37 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ccce20>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': / | asctime=2025-02-04 11:46:37 levelname=WARNING taskName=null
Starting new HTTP connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:46:38 levelname=DEBUG taskName=null
Failed connection attempt with HTTP | asctime=2025-02-04 11:46:53 levelname=DEBUG taskName=null
Starting new HTTPS connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:46:53 levelname=DEBUG taskName=null
Incremented Retry for (url='/'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:47:08 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc6c3cac050>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': / | asctime=2025-02-04 11:47:08 levelname=WARNING taskName=null
Starting new HTTPS connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:47:08 levelname=DEBUG taskName=null
Failed connection attempt with HTTPS | asctime=2025-02-04 11:47:23 levelname=DEBUG taskName=null
Using HTTP scheme | asctime=2025-02-04 11:47:23 levelname=DEBUG taskName=null
Base URL: http://192.168.10.20:5000/ | asctime=2025-02-04 11:47:23 levelname=DEBUG taskName=null
Starting new HTTP connection (1): 192.168.10.20:5000 | asctime=2025-02-04 11:47:23 levelname=DEBUG taskName=null
Incremented Retry for (url='/api/v2/torrents/info'): Retry(total=0, connect=0, read=1, redirect=None, status=None) | asctime=2025-02-04 11:47:38 levelname=DEBUG taskName=null
Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ccd590>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)')': /api/v2/torrents/info | asctime=2025-02-04 11:47:38 levelname=WARNING taskName=null
Starting new HTTP connection (2): 192.168.10.20:5000 | asctime=2025-02-04 11:47:38 levelname=DEBUG taskName=null
Failed to connect to qBittorrent. Unknown Error: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.10.20', port=5014): Max retries exceeded with url: /api/v2/torrents/info (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ccd8c0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)'))")) | asctime=2025-02-04 11:47:53 levelname=DEBUG taskName=null
Couldn't fetch torrents: Failed to connect to qBittorrent. Unknown Error: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.10.20', port=5014): Max retries exceeded with url: /api/v2/torrents/info (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c3ccd8c0>, 'Connection to 192.168.10.20 timed out. (connect timeout=15.1)'))")) | asctime=2025-02-04 11:47:53 levelname=ERROR taskName=null
Exporter listening on 0.0.0.0:8000 | asctime=2025-02-04 11:47:53 levelname=INFO taskName=null

```

**Comment by MrE12345** [comment]
QbitAre you using port 5000 to access webui? In your docker-compose you have set the port to 5010.
Also use ip address instead of name in prometheus.yaml. Also point it to the exporter, not qbit

**Comment by esanchezm** [comment]
Hey! Thanks for your interest and for taking time to open the issue.

It's unrelated to the exporter and it's more like an issue with your setup. **For that reason, I'm closing the bug**, but we can keep talking if you want, hope you can understand 😄 

You're getting a timeout, which means it can't connect at all. So let's try to figure out where's the issue...

When you mean you're running `arch-qbittorrentvpn` on another stack what do you mean? is it in another docker compose? Are they running in the same server? And in the same docker network?

I can see a couple of issues, but I think they might not be the issue as it's a connectivity issue between the exporter and the qbittorrent server.

1. You set this value, but qbittorrent is listening on port 5000. It's strange because logs say it connects to port `5000`
```yaml
    - QBITTORRENT_PORT=5010
```
2. Prometheus should scrape the exporter but you're pointing it to the qbittorrent server.
```yaml
  - job_name: "qbittorrent_exporter"
    static_configs:
        - targets: ['arch-qbittorrentvpn:5000']
```
should be

```yaml
  - job_name: "qbittorrent_exporter"
    static_configs:
        - targets: ['prometheus-qbittorrent-exporter:7001']
```

3. This is not important but the exporter needs no config directory, you can remove this from the `prometheus-qbittorrent-exporter`:
```
    volumes:
      - /path/to/Grafana/Prometheus:/config
```
